(()=>{
'use strict';
const RF={};
const C={IN:0.0254,FIELD:144*0.0254,DT:1/120,MAX_FRAME:.05,G:9.80665,DEG:Math.PI/180,RAD:180/Math.PI,RHO:1.225};
const T={artifactD:4.9*C.IN,artifactM:.0748,rest:.42,wallRest:.35,roll:.03,dragCd:.5,slip:.82,robotW:18*C.IN,robotH:18*C.IN,intR:.045};
const el=id=>document.getElementById(id), clamp=(v,a,b)=>Math.max(a,Math.min(b,v)), inM=n=>n*C.IN, len=(x,y)=>Math.hypot(x,y);
function toast(t){let n=el('toast');n.textContent=t;n.classList.add('show');clearTimeout(toast.t);toast.t=setTimeout(()=>n.classList.remove('show'),2200)}
function log(t,err=false){let d=document.createElement('div');d.className=err?'line error':'line';d.textContent=t;el('terminal').appendChild(d);el('terminal').scrollTop=el('terminal').scrollHeight}
function rng(seed){let s=seed>>>0;return()=>((s=(1664525*s+1013904223)>>>0)/4294967296)}
function rot(x,y,a){let c=Math.cos(a),s=Math.sin(a);return{x:x*c-y*s,y:x*s+y*c}}
function wrap(a){while(a>Math.PI)a-=2*Math.PI;while(a<-Math.PI)a+=2*Math.PI;return a}
const RP={qualifier:{movement:16,goal:36,pattern:18},regional:{movement:21,goal:42,pattern:22},championship:{movement:21,goal:67,pattern:22}};
const F={w:C.FIELD,h:C.FIELD,tile:inM(24),artR:T.artifactD/2,goals:{blue:{x:inM(18),y:inM(24),w:inM(27),h:inM(27),lip:inM(38.75),z:inM(42)},red:{x:inM(99),y:inM(24),w:inM(27),h:inM(27),lip:inM(38.75),z:inM(42)}},classifiers:{blue:{x:inM(18),y:inM(54),w:inM(27),h:inM(12)},red:{x:inM(99),y:inM(54),w:inM(27),h:inM(12)}},gates:{blue:{x:inM(47),y:inM(55),w:inM(2.75),h:inM(10)},red:{x:inM(95),y:inM(55),w:inM(2.75),h:inM(10)}},depot:{blue:{x:inM(5),y:inM(104),w:inM(33),h:inM(24)},red:{x:inM(106),y:inM(104),w:inM(33),h:inM(24)}},base:{blue:{x:inM(5),y:inM(130),w:inM(33),h:inM(12)},red:{x:inM(106),y:inM(130),w:inM(33),h:inM(12)}},tunnel:{blue:{x:inM(46),y:inM(70),w:inM(18),h:inM(8)},red:{x:inM(80),y:inM(70),w:inM(18),h:inM(8)}},spawns:[{x:inM(56),y:inM(20)},{x:inM(72),y:inM(20)},{x:inM(88),y:inM(20)},{x:inM(56),y:inM(124)},{x:inM(72),y:inM(124)},{x:inM(88),y:inM(124)}],motifs:['GPP','PGP','PPG']};
function inside(r,p,pad=0){return p.x>=r.x-pad&&p.x<=r.x+r.w+pad&&p.y>=r.y-pad&&p.y<=r.y+r.h+pad}function center(r){return{x:r.x+r.w/2,y:r.y+r.h/2}}
function input(){return{forward:0,back:0,left:0,right:0,turnLeft:0,turnRight:0,gate:0}}
function robot(){let m=16,I=m*(T.robotW*T.robotW+T.robotH*T.robotH)/12;return{x:inM(24),y:inM(120),th:0,vx:0,vy:0,om:0,w:T.robotW,h:T.robotH,m,im:1/m,I,iI:1/I,inv:[],intake:false,fly:0,trail:[],left:false,park:false}}
function artifact(id,color,x,y,r){let rad=F.artR+(r()-.5)*inM(.25);return{id,color,state:'loose',x,y,z:rad,vx:0,vy:0,vz:0,spin:0,r:rad,m:T.artifactM,im:1/T.artifactM}}
function world(seed=20260426){let r=rng(seed),colors=[];for(let i=0;i<24;i++)colors.push('purple');for(let i=0;i<12;i++)colors.push('green');for(let i=colors.length-1;i>0;i--){let j=Math.floor(r()*(i+1));[colors[i],colors[j]]=[colors[j],colors[i]]}let arts=[],id=1;colors.forEach((c,k)=>{let s=F.spawns[k%F.spawns.length],col=Math.floor(k/F.spawns.length);arts.push(artifact('a'+id++,c,s.x+((col%3)-1)*inM(5)+(r()-.5)*inM(1.5),s.y+Math.floor(col/3)*inM(6)+(r()-.5)*inM(1.5),r))});return{rng:r,time:0,paused:false,phase:'teleop',input:input(),robot:robot(),artifacts:arts,projectiles:[],gates:{blue:{...F.gates.blue,open:0,was:false},red:{...F.gates.red,open:0,was:false}},classifiers:{blue:{slots:[],overflow:0},red:{slots:[],overflow:0}},score:{auto:0,teleop:0,movement:0,goal:0,pattern:0,depot:0,rp:0},motif:F.motifs[Math.floor(r()*F.motifs.length)],tier:'qualifier',auto:null,fps:0,bus:12.6,driverMode:true}}
let W=world();
function cfg(){let n=(id,d)=>{let v=Number(el(id)?.value);return Number.isFinite(v)?v:d};return{mass:n('robotMassKg',16),rpm:n('driveMotorRpm',312),wheel:n('driveWheelMm',96)/1000,mu:n('tractionMu',.85),bat:n('batteryVoltage',12.6),shotRpm:n('shooterRpm',2100),shotWheel:n('shooterWheelMm',90)/1000,angle:n('shotAngleDeg',42)*C.DEG}}
function obstacles(){let o=[];for(let a of ['blue','red']){o.push({...F.goals[a],kind:'goal'});o.push({...F.classifiers[a],kind:'classifier'});if(W.gates[a].open<.92)o.push({...F.gates[a],kind:'gate'})}return o}
function keepRobot(r){let rad=Math.SQRT2*Math.max(r.w,r.h)/2;r.x=clamp(r.x,rad,C.FIELD-rad);r.y=clamp(r.y,rad,C.FIELD-rad)}
function stepRobot(dt){let r=W.robot,c=cfg();r.m=c.mass;r.im=1/c.mass;r.I=c.mass*(r.w*r.w+r.h*r.h)/12;r.iI=1/r.I;let top=(c.rpm/60)*Math.PI*c.wheel*.72*clamp(c.bat/12.6,.55,1.08),maxA=c.mu*C.G*.92,maxO=4.2*(c.bat/12.6),maxAl=9*(c.bat/12.6);let f=W.input.forward-W.input.back,s=W.input.right-W.input.left,t=W.input.turnRight-W.input.turnLeft,m=len(f,s);if(m>1){f/=m;s/=m}let dx=s*top,dy=-f*top;if(el('controlMode').value==='robot'){let q=rot(dx,dy,r.th);dx=q.x;dy=q.y}let ax=dx-r.vx,ay=dy-r.vy,al=len(ax,ay)/dt;if(al>maxA){ax=ax/al*maxA;ay=ay/al*maxA}r.vx+=ax*dt;r.vy+=ay*dt;let desOm=t*maxO,dO=clamp((desOm-r.om)/dt,-maxAl,maxAl);r.om+=dO*dt;r.vx*=Math.pow(.72,dt);r.vy*=Math.pow(.72,dt);r.om*=Math.pow(.55,dt);r.x+=r.vx*dt;r.y+=r.vy*dt;r.th=wrap(r.th+r.om*dt);keepRobot(r);if(len(r.vx,r.vy)>.01){let p=r.trail[r.trail.length-1];if(!p||len(p.x-r.x,p.y-r.y)>inM(2)){r.trail.push({x:r.x,y:r.y});if(r.trail.length>600)r.trail.shift()}}let current=(len(ax,ay)/Math.max(.1,maxA))*28+Math.abs(dO/maxAl)*10;W.bus=clamp(c.bat-T.intR*current,8,13.2);r.fly+=(c.shotRpm*2*Math.PI/60*(c.bat/12.6)-r.fly)*(1-Math.exp(-dt/.65))}
function collideWalls(a){let r=a.r;if(a.x<r){a.x=r;a.vx=Math.abs(a.vx)*T.wallRest}if(a.x>C.FIELD-r){a.x=C.FIELD-r;a.vx=-Math.abs(a.vx)*T.wallRest}if(a.y<r){a.y=r;a.vy=Math.abs(a.vy)*T.wallRest}if(a.y>C.FIELD-r){a.y=C.FIELD-r;a.vy=-Math.abs(a.vy)*T.wallRest}}
function collideStatic(a){for(let R of obstacles()){let cx=clamp(a.x,R.x,R.x+R.w),cy=clamp(a.y,R.y,R.y+R.h),dx=a.x-cx,dy=a.y-cy,d=len(dx,dy);if(d<a.r){let nx=d>1e-8?dx/d:1,ny=d>1e-8?dy/d:0,pen=a.r-d;a.x+=nx*pen;a.y+=ny*pen;let vn=a.vx*nx+a.vy*ny;if(vn<0){a.vx-=(1+T.wallRest)*vn*nx;a.vy-=(1+T.wallRest)*vn*ny;a.vx*=.82;a.vy*=.82}}}}
function circ(a,b){let dx=b.x-a.x,dy=b.y-a.y,d=len(dx,dy),md=a.r+b.r;if(d<=1e-9||d>=md)return;let nx=dx/d,ny=dy/d,pen=md-d,inv=a.im+b.im;a.x-=nx*pen*a.im/inv;a.y-=ny*pen*a.im/inv;b.x+=nx*pen*b.im/inv;b.y+=ny*pen*b.im/inv;let rvx=b.vx-a.vx,rvy=b.vy-a.vy,vn=rvx*nx+rvy*ny;if(vn>0)return;let j=-(1+T.rest)*vn/inv,ix=j*nx,iy=j*ny;a.vx-=ix*a.im;a.vy-=iy*a.im;b.vx+=ix*b.im;b.vy+=iy*b.im}
function robotArtifact(a){let r=W.robot,rel=rot(a.x-r.x,a.y-r.y,-r.th),hx=r.w/2,hy=r.h/2,cx=clamp(rel.x,-hx,hx),cy=clamp(rel.y,-hy,hy),dx=rel.x-cx,dy=rel.y-cy,d=len(dx,dy);if(d>=a.r)return;let nloc=d>1e-8?{x:dx/d,y:dy/d}:{x:0,y:-1},n=rot(nloc.x,nloc.y,r.th),pen=a.r-d;a.x+=n.x*pen;a.y+=n.y*pen;r.x-=n.x*pen*.08;r.y-=n.y*pen*.08;let rvx=a.vx-r.vx,rvy=a.vy-r.vy,vn=rvx*n.x+rvy*n.y;if(vn<0){let inv=a.im+r.im,j=-(1+.12)*vn/inv;a.vx+=j*n.x*a.im;a.vy+=j*n.y*a.im;r.vx-=j*n.x*r.im;r.vy-=j*n.y*r.im;a.vx+=n.x*len(r.vx,r.vy)*.18;a.vy+=n.y*len(r.vx,r.vy)*.18}}
function robotStatic(){let r=W.robot,rad=Math.SQRT2*Math.max(r.w,r.h)/2*.92;for(let R of obstacles()){let cx=clamp(r.x,R.x,R.x+R.w),cy=clamp(r.y,R.y,R.y+R.h),dx=r.x-cx,dy=r.y-cy,d=len(dx,dy);if(d<rad){let nx=d>1e-8?dx/d:1,ny=d>1e-8?dy/d:0,pen=rad-d;r.x+=nx*pen;r.y+=ny*pen;let vn=r.vx*nx+r.vy*ny;if(vn<0){r.vx-=1.2*vn*nx;r.vy-=1.2*vn*ny;r.vx*=.65;r.vy*=.65}}}}
function stepArtifacts(dt){let loose=W.artifacts.filter(a=>a.state==='loose');for(let a of loose){a.x+=a.vx*dt;a.y+=a.vy*dt;let sp=len(a.vx,a.vy);if(sp>1e-6){let ns=Math.max(0,sp-T.roll*C.G*dt),k=ns/sp;a.vx*=k;a.vy*=k}collideWalls(a);collideStatic(a)}for(let i=0;i<loose.length;i++)for(let j=i+1;j<loose.length;j++)circ(loose[i],loose[j]);for(let a of loose)robotArtifact(a);robotStatic()}
function intake(){let r=W.robot;if(!r.intake||r.inv.length>=4)return;let mouth=rot(0,-r.h/2-inM(2),r.th);mouth.x+=r.x;mouth.y+=r.y;for(let a of W.artifacts){if(r.inv.length>=4)break;if(a.state!=='loose'||a.z>a.r*1.4)continue;if(len(a.x-mouth.x,a.y-mouth.y)<inM(7)&&len(a.vx-r.vx,a.vy-r.vy)<2.5){a.state='carried';a.vx=a.vy=0;r.inv.push(a.id);log('Intake captured '+a.color+' artifact.')}}}
function addScore(bucket,p){if(W.phase==='auto')W.score.auto+=p;else W.score.teleop+=p;W.score[bucket]=(W.score[bucket]||0)+p}
function release(alliance){let cl=W.classifiers[alliance],tun=F.tunnel[alliance];let n=0;for(let id of cl.slots.splice(0)){let a=W.artifacts.find(x=>x.id===id);if(a){a.state='loose';a.x=tun.x+tun.w/2;a.y=tun.y+tun.h/2;a.vx=(alliance==='blue'?1:-1)*(0.6+W.rng()*.8);a.vy=(W.rng()-.5)*.35;n++}}if(n)log('Gate released '+n+' classified artifacts.')}
function stepGates(dt){for(let k of ['blue','red']){let g=W.gates[k],R=F.gates[k],near=inside({x:R.x-inM(5),y:R.y-inM(5),w:R.w+inM(10),h:R.h+inM(10)},W.robot),push=near&&len(W.robot.vx,W.robot.vy)>.18;if(W.input.gate||push)g.open=clamp(g.open+dt*2.2,0,1);else g.open=clamp(g.open-dt*.9,0,1);if(g.open>.95&&!g.was){release(k);g.was=true;log(k.toUpperCase()+' gate opened.')}if(g.open<.2)g.was=false}}
function shoot(alliance='blue',power=.9,angleDeg=null){let r=W.robot;if(!r.inv.length){log('Cannot shoot: inventory empty.',true);return}let c=cfg(),ang=(angleDeg==null?Number(el('shotAngleDeg').value):angleDeg)*C.DEG,exit=r.fly*(c.shotWheel/2)*T.slip*clamp(power,.1,1);let id=r.inv.shift(),a=W.artifacts.find(x=>x.id===id),color=a?a.color:'purple';if(a)a.state='launched';let tar=center(F.goals[alliance]),yaw=Math.atan2(tar.y-r.y,tar.x-r.x);W.projectiles.push({id:'p'+Math.floor(W.rng()*1e9),color,r:F.artR,m:T.artifactM,x:r.x+Math.cos(yaw)*inM(8),y:r.y+Math.sin(yaw)*inM(8),z:inM(12),vx:Math.cos(yaw)*exit*Math.cos(ang)+r.vx,vy:Math.sin(yaw)*exit*Math.cos(ang)+r.vy,vz:exit*Math.sin(ang),spin:r.fly*.12});log('Shot '+color+' toward '+alliance+' at '+exit.toFixed(2)+' m/s.')}
function stepProj(dt){let c=cfg();for(let p of W.projectiles){if(p.dead)continue;let area=Math.PI*p.r*p.r,sp=Math.hypot(p.vx,p.vy,p.vz);if(sp>1e-6){let D=.5*C.RHO*T.dragCd*area*sp*sp;p.vx+=-D*p.vx/sp/p.m*dt;p.vy+=-D*p.vy/sp/p.m*dt;p.vz+=(-C.G-D*p.vz/sp/p.m)*dt}else p.vz-=C.G*dt;p.x+=p.vx*dt;p.y+=p.vy*dt;p.z+=p.vz*dt;goalHit(p);if(p.z<=p.r&&!p.dead){p.dead=true;let a=artifact('miss'+Math.floor(W.rng()*1e9),p.color,p.x,p.y,W.rng);a.vx=p.vx*.55;a.vy=p.vy*.55;W.artifacts.push(a);log('Shot landed loose.',true)}}W.projectiles=W.projectiles.filter(p=>!p.remove)}
function goalHit(p){for(let al of ['blue','red']){let G=F.goals[al];if(inside(G,p)&&p.z>G.lip){p.dead=true;p.remove=true;let cl=W.classifiers[al],speed=Math.hypot(p.vx,p.vy,p.vz),overflow=speed>6||Math.abs(p.spin)>60;if(cl.slots.length<9&&!overflow){let a=artifact('class'+Math.floor(W.rng()*1e9),p.color,0,0,W.rng);a.state='classified';cl.slots.push(a.id);W.artifacts.push(a);addScore('goal',4);log('CLASSIFIED '+p.color+' for '+al+'.')}else{cl.overflow++;addScore('goal',1);log('OVERFLOW artifact for '+al+'.')}}}}
function rules(){let r=W.robot;if(!r.left&&len(r.x-inM(24),r.y-inM(120))>inM(6)){r.left=true;addScore('movement',5)}for(let al of ['blue','red'])if(inside(F.base[al],r,Math.max(r.w,r.h)/2)&&!r.park){r.park=true;addScore('movement',10);log('BASE reached.')}let best=0;for(let al of ['blue','red']){let s=W.classifiers[al].slots.map(id=>W.artifacts.find(a=>a.id===id)).filter(Boolean).map(a=>a.color==='green'?'G':'P').join('');for(let i=0;i<=s.length-3;i++)if(s.slice(i,i+3)===W.motif)best+=10}W.score.pattern=best;let th=RP[W.tier],rp=0;if(W.score.movement>=th.movement)rp++;if(W.score.goal>=th.goal)rp++;if(W.score.pattern>=th.pattern)rp++;if(r.left&&r.park)rp++;W.score.rp=rp}
function scoreDepot(){let r=W.robot;if(!r.inv.length){log('Depot score failed: inventory empty.',true);return}let near=inside(F.depot.blue,r,Math.max(r.w,r.h)/2)||inside(F.depot.red,r,Math.max(r.w,r.h)/2);if(!near){log('Depot score failed: robot is not in a DEPOT.',true);return}let n=r.inv.length;for(let id of r.inv){let a=W.artifacts.find(x=>x.id===id);if(a)a.state='depot'}r.inv=[];addScore('depot',n*2);log('Depot scored '+n+' artifacts.')}
function step(dt){if(W.paused)return;if(W.auto)stepAuto(dt);stepRobot(dt);stepProj(dt);stepArtifacts(dt);intake();stepGates(dt);rules();W.time+=dt}
function parseAuto(){return el('autoEditor').value.split('\n').map((raw,i)=>{let line=raw.split('#')[0].trim();if(!line)return null;let p=line.split(/\s+/);return{cmd:p[0].toUpperCase(),args:p.slice(1),line:i+1}}).filter(Boolean)}
function startAuto(){W.auto={cmds:parseAuto(),i:0,t:0,cur:null};W.phase='auto';toast('Auto started');log('Auto started.')}
function stopAuto(){W.auto=null;Object.assign(W.input,input());W.robot.intake=false;W.phase='teleop';log('Auto stopped.')}
function stepAuto(dt){let A=W.auto;if(!A)return;if(A.cur){A.t-=dt;if(A.t>0)return;Object.assign(W.input,input());A.cur=null;A.i++}if(A.i>=A.cmds.length){stopAuto();toast('Auto complete');return}let it=A.cmds[A.i],a=it.args,r=W.robot;switch(it.cmd){case'SET_START':r.x=inM(+a[0]||24);r.y=inM(+a[1]||120);r.th=(+a[2]||0)*C.DEG;r.vx=r.vy=r.om=0;A.i++;break;case'DRIVE':{let f=+a[0]||0,s=+a[1]||0,t=+a[2]||0;W.input.forward=f>0;W.input.back=f<0;W.input.right=s>0;W.input.left=s<0;W.input.turnRight=t>0;W.input.turnLeft=t<0;A.cur=it;A.t=Math.max(0,+a[3]||0);break}case'TURN':{let d=+a[0]||0,p=clamp(+a[1]||.6,.1,1);W.input.turnRight=d>0;W.input.turnLeft=d<0;A.cur=it;A.t=Math.abs(d)/(180*p);break}case'INTAKE':case'INTAKE_ON':r.intake=true;A.i++;break;case'INTAKE_OFF':r.intake=false;A.i++;break;case'WAIT':A.cur=it;A.t=Math.max(0,+a[0]||0);break;case'PUSH_GATE':case'OPEN_GATE':W.input.gate=true;A.cur=it;A.t=Math.max(.2,+a[0]||.7);break;case'SHOOT':shoot((a[0]||'blue').toLowerCase(),+a[1]||.9,+a[2]||null);A.i++;break;case'SCORE_DEPOT':scoreDepot();A.i++;break;default:log('Unknown auto command line '+it.line+': '+it.cmd,true);A.i++}}
const canvas=el('fieldCanvas'),ctx=canvas.getContext('2d'),S=canvas.width/C.FIELD;function px(v){return v*S}function rect(R,fill,stroke,label){ctx.fillStyle=fill;ctx.strokeStyle=stroke;ctx.lineWidth=2;ctx.fillRect(px(R.x),px(R.y),px(R.w),px(R.h));ctx.strokeRect(px(R.x),px(R.y),px(R.w),px(R.h));ctx.fillStyle=stroke;ctx.font='700 10px Arial';ctx.fillText(label,px(R.x)+5,px(R.y)+13)}
function render(){ctx.clearRect(0,0,canvas.width,canvas.height);ctx.fillStyle='#252a31';ctx.fillRect(0,0,canvas.width,canvas.height);ctx.strokeStyle='rgba(255,255,255,.13)';ctx.lineWidth=1;for(let i=0;i<=6;i++){let p=px(inM(24*i));ctx.beginPath();ctx.moveTo(p,0);ctx.lineTo(p,canvas.height);ctx.stroke();ctx.beginPath();ctx.moveTo(0,p);ctx.lineTo(canvas.width,p);ctx.stroke()}ctx.strokeStyle='white';ctx.lineWidth=4;ctx.strokeRect(0,0,canvas.width,canvas.height);for(let al of ['blue','red']){let col=al==='blue'?'#60a5fa':'#fca5a5',bg=al==='blue'?'rgba(37,99,235,.32)':'rgba(239,68,68,.32)';rect(F.goals[al],bg,col,'GOAL');rect(F.classifiers[al],'rgba(255,255,255,.08)',col,'CLASSIFIER');rect(F.depot[al],al==='blue'?'rgba(37,99,235,.12)':'rgba(239,68,68,.12)',col,'DEPOT');rect(F.base[al],al==='blue'?'rgba(37,99,235,.18)':'rgba(239,68,68,.18)',col,'BASE');rect(F.gates[al],W.gates[al].open>.9?'rgba(134,239,172,.5)':'rgba(251,113,133,.45)',W.gates[al].open>.9?'#86efac':'#fb7185','GATE')}rect(F.tunnel.blue,'rgba(37,99,235,.1)','#60a5fa','TUNNEL');rect(F.tunnel.red,'rgba(239,68,68,.1)','#fca5a5','TUNNEL');let r=W.robot;if(r.trail.length>1){ctx.strokeStyle='rgba(103,232,249,.82)';ctx.lineWidth=2;ctx.beginPath();ctx.moveTo(px(r.trail[0].x),px(r.trail[0].y));for(let p of r.trail)ctx.lineTo(px(p.x),px(p.y));ctx.stroke()}for(let a of W.artifacts){if(a.state!=='loose')continue;ctx.save();ctx.translate(px(a.x),px(a.y));ctx.fillStyle=a.color==='green'?'#22c55e':'#c084fc';ctx.strokeStyle='rgba(0,0,0,.65)';ctx.lineWidth=2;ctx.beginPath();ctx.arc(0,0,px(a.r),0,Math.PI*2);ctx.fill();ctx.stroke();ctx.restore()}for(let p of W.projectiles){let z=Math.max(0,px(p.z)*.35);ctx.save();ctx.globalAlpha=.22;ctx.fillStyle='#000';ctx.beginPath();ctx.ellipse(px(p.x),px(p.y)+z*.25,px(p.r)*.75,px(p.r)*.35,0,0,Math.PI*2);ctx.fill();ctx.globalAlpha=1;ctx.fillStyle=p.color==='green'?'#22c55e':'#c084fc';ctx.beginPath();ctx.arc(px(p.x),px(p.y)-z,px(p.r),0,Math.PI*2);ctx.fill();ctx.restore()}ctx.save();ctx.translate(px(r.x),px(r.y));ctx.rotate(r.th);ctx.fillStyle='rgba(103,232,249,.28)';ctx.strokeStyle='#67e8f9';ctx.lineWidth=3;ctx.beginPath();ctx.roundRect(-px(r.w)/2,-px(r.h)/2,px(r.w),px(r.h),8);ctx.fill();ctx.stroke();ctx.fillStyle='#67e8f9';ctx.beginPath();ctx.moveTo(0,-px(r.h)/2-10);ctx.lineTo(-10,-px(r.h)/2+10);ctx.lineTo(10,-px(r.h)/2+10);ctx.fill();if(r.intake){ctx.strokeStyle='#86efac';ctx.lineWidth=4;ctx.strokeRect(-px(r.w)*.28,-px(r.h)/2-18,px(r.w)*.56,16)}ctx.restore()}
function hud(){let r=W.robot,total=W.score.auto+W.score.teleop+W.score.goal+W.score.depot+W.score.pattern;el('simTimeStat').textContent=W.time.toFixed(2);el('busVoltageStat').textContent=W.bus.toFixed(1)+'V';el('speedStat').textContent=len(r.vx,r.vy).toFixed(2);el('inventoryStat').textContent=r.inv.length+'/4';el('classifiedStat').textContent=(W.classifiers.blue.slots.length+W.classifiers.red.slots.length)+'/9';el('overflowStat').textContent=W.classifiers.blue.overflow+W.classifiers.red.overflow;el('scoreStat').textContent=total;el('rpStat').textContent=W.score.rp;el('motifStat').textContent=W.motif}
function bind(){el('themeButton').onclick=()=>{let l=document.body.classList.toggle('light');el('themeButton').textContent=l?'Dark Mode':'Light Mode'};el('driverModeButton').onclick=()=>{W.driverMode=!W.driverMode;el('driverModeButton').textContent=W.driverMode?'Driver Mode: On':'Driver Mode: Off'};el('pauseButton').onclick=()=>{W.paused=!W.paused;el('pauseButton').textContent=W.paused?'Resume':'Pause'};el('clearTrailButton').onclick=()=>W.robot.trail=[];el('resetAllButton').onclick=()=>{W=world();bindInput();toast('Reset')};el('runAutoButton').onclick=startAuto;el('runAutoTopButton').onclick=startAuto;el('runAutoPanelButton').onclick=startAuto;el('stopAutoButton').onclick=stopAuto;el('sampleAutoButton').onclick=()=>toast('Sample already loaded');el('shootBlueButton').onclick=()=>shoot('blue');el('shootRedButton').onclick=()=>shoot('red');el('scoreDepotButton').onclick=scoreDepot;el('eventTier').onchange=e=>W.tier=e.target.value;el('clearLogButton').onclick=()=>el('terminal').innerHTML='<div class="line">Log cleared.</div>';el('exportStateButton').onclick=()=>{navigator.clipboard?.writeText(JSON.stringify({time:W.time,score:W.score,robot:W.robot,classifiers:W.classifiers},null,2));toast('State copied')};let gate=el('openGateButton');gate.onpointerdown=()=>W.input.gate=1;gate.onpointerup=()=>W.input.gate=0;gate.onpointerleave=()=>W.input.gate=0}
function bindInput(){let map={w:'forward',s:'back',a:'left',d:'right',q:'turnLeft',e:'turnRight'},typing=()=>['TEXTAREA','INPUT','SELECT'].includes(document.activeElement?.tagName);window.onkeydown=e=>{let k=e.key.toLowerCase();if(map[k]){if(typing()&&!W.driverMode)return;e.preventDefault();W.input[map[k]]=1;pad()}if(e.code==='Space'&&!typing()){e.preventDefault();W.robot.intake=true;pad()}};window.onkeyup=e=>{let k=e.key.toLowerCase();if(map[k]){e.preventDefault();W.input[map[k]]=0;pad()}if(e.code==='Space'){W.robot.intake=false;pad()}};document.querySelectorAll('[data-drive]').forEach(b=>{let key=b.dataset.drive;b.onpointerdown=e=>{e.preventDefault();W.input[key]=1;pad()};b.onpointerup=e=>{e.preventDefault();W.input[key]=0;pad()};b.onpointerleave=e=>{W.input[key]=0;pad()}});let ib=el('intakeButton');ib.onpointerdown=e=>{e.preventDefault();W.robot.intake=true;pad()};ib.onpointerup=e=>{W.robot.intake=false;pad()};ib.onpointerleave=e=>{W.robot.intake=false;pad()}}
function pad(){for(let k of ['forward','back','left','right','turnLeft','turnRight'])document.querySelector(`[data-drive="${k}"]`)?.classList.toggle('active',!!W.input[k]);el('intakeButton').classList.toggle('active',W.robot.intake)}
bind();bindInput();let acc=0,last=performance.now()/1000,fa=0,ff=0,fl=last;function loop(ms){let now=ms/1000,ft=Math.min(C.MAX_FRAME,now-last);last=now;acc+=ft;while(acc>=C.DT){step(C.DT);acc-=C.DT}render();hud();ff++;fa+=ft;if(now-fl>.5){W.fps=ff/fa;el('fpsStat').textContent=W.fps.toFixed(0);ff=0;fa=0;fl=now}requestAnimationFrame(loop)}requestAnimationFrame(loop);toast('Canvas physics simulator loaded');
})();
